name: Build and Deploy Static Web App to Azure - SBSBINTRANET

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Static Web App
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install npm dependencies and build
        run: |
          npm install
          npm run build --if-present

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"  # Location of your app source code
          output_location: "build"  # Adjust to the actual build output folder
          deployment_action: "upload"  # Explicitly setting deployment action
