name: Build and Deploy Static Web App to Azure - SBSBINTRANET

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Static Web App
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Disable Oryx build process by skipping the build explicitly
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_BUSH_0F99F2E10 }}
          app_location: "/"  # Points to the root of your app where index.html is located
          output_location: ""  # No build output directory required
          skip_app_build: true  # Skip the app build process
          deployment_action: "upload"  # Explicitly set the deployment action to upload
